base:
  titre: "Christophe Rubeck: Data Scientist"
  url: "http://rubeck.christophe.free.fr/"
  description: |
    Bienvenue sur le Curriculum Vitae de Christophe Rubeck, Data Scientist, spécialiste en analyse de données, modélisation, et machine learning.
  google_key: "GMDGqJyP4roEHJwDaANDACPNu-ygvlmy5CrXF7mP-d0"
  menu:
    - "accueil"
    - "competences"
    - "experiences"
    - "formation"
    - "interet"
    - "reseaux"
    - "publications"
  pages:
    - accueil: "Accueil"
      experiences: "Expériences"
      competences: "Compétences"
      formation: "Formations"
      interet: "Centres d'intêrets"
      publications: "Publications"
      these: "Travaux de thèse"
      reseaux: "Réseaux"
      404: "Erreur 404"